### ISSUE TITLE
Source Code regarding the similarity threshold 

### ISSUE THREAD

**Issue by yq790** [tue-mps/algm-segmenter#1]
Greetings,

Thank you for your excellent work! 

The threshold values seem already available in the training commands. Will you post the code for selecting the optimal threshold based on a pre-trained baseline model and a training dataset?

Thank you!

**Comment by narsisn** [comment]
Hi,
Thanks for your interest in our work!

Yes, I'll share the code for selecting the optimal threshold in the next few months. In the meantime, you can easily do it yourself by extracting tokens from the first layer, calculating similarities to find the threshold.
